name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        d:
          - "ldc-latest"
          - "dmd-master"
        meson:
          - 1.8.0
        ninja:
          - latest
        exclude:
          - os: macos-latest
            d: "dmd-master"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Cache
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.dub
            ~/AppData/Local/dub
            ~/.cache/pip
            ~/AppData/Local/pip/cache
          key: "containers-cache-OS:${{ matrix.os }}-D:${{ matrix.d }}-${{ matrix.meson }}-${{ matrix.ninja }}-deps:${{ hashFiles('./meson.build') }}-${{ hashFiles('./dub.sdl') }}"

      # Setup compilers and tools

      - name: Setup D
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.d }}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Setup Meson
        run: pip install meson==${{ matrix.meson }}

      - name: Setup Ninja
        uses: lukka/get-cmake@latest
        with:
          ninjaVersion: ${{ matrix.ninja }}

      # Build and Test

      - name: Build documentation
        run: |
          dub build --build=ddox
          dub build --build=docs

      - name: Build
        run: |
          meson setup ./build
          meson compile -C ./build

      - name: Install gcc-multilib
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt-get install -y gcc-multilib

      - name: Make Test
        run: |
          make -B -C test/

      # TODO it fails to run the UnrolledList test on ldc
      - name: Dub Test
        run: |
          dub test